[package]
name = "vip-712"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
repository = "https://github.com/openvapory/tetsy-vapory"
documentation = "https://docs.rs/vip-712"
readme = "README.md"
description = "vip-712 encoding"
keywords = ["vip-712", "vip712", "vip"]
license = "GPL-3.0"
edition = "2018"
homepage = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
vapabi = "9.0.1"
tetsy-keccak-hash = "0.4.0"
vapory-types = "0.8.0"
failure = "0.1"
itertools = "0.7"
lazy_static = "1.1"
regex = "1.0"
validator = "0.8"
validator_derive = "0.8"
lunarity-lexer = "0.2"
rustc-hex = "2.0"
indexmap = "1.0.2"
