[package]
description = "Tetsy Vapory Key Management CLI"
name = "vapstore-cli"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
license = "GPL-3.0"
documentation = "https://docs.rs/vapstore-cli"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
docopt = "1.0"
env_logger = "0.5"
num_cpus = "1.6"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
parking_lot = "0.9"
vapstore = { version = "0.2.1", path = "../" }
vapkey = { version = "0.4.0", path = "../../vapkey" }
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
dir = { version = "0.1.2", path = '../../../util/dir' }
panic-hook = { version = "0.1.0", path = "../../../util/panic-hook" }

[[bin]]
name = "vapstore"
path = "src/main.rs"
doc = false

[dev-dependencies]
tempdir = "0.3"
