[package]
description = "Basic PoA blockchain engine."
name = "basic-authority"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { version = "0.1.0", path = "../../client-traits" }
common-types = { version = "0.1.0", path = "../../types" }
enjen = { version = "0.1.0", path = "../../enjen" }
vapory-types = "0.8.0"
vapjson = { path = "../../../json" }
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
log = "0.4.8"
mashina = { version = "0.1.0", path = "../../mashina" }
parking_lot = "0.9"
tetsy-rlp = "0.4.5"
validator-set = { path = "../validator-set" }

[dev-dependencies]
accounts = { package = "vapcore-accounts", path = "../../../accounts" }
enjen = { version = "0.1.0", path = "../../enjen", features = ["test-helpers"] }
vapcore = { path = "../..", features = ["test-helpers"] }
tetsy-keccak-hash = "0.4.0"
tempdir = "0.3"
vapcore-spec = { version = "0.1.0", path = "../../spec" }

[features]
test-helpers = []
