[package]
name = "triehash-vapory"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Trie-root helpers, vapory style"
license = "GPL-3.0"

[dependencies]
# tetsy-triehash = "0.8.4"
vapory-types = "0.8.0"
tetsy-keccak-hasher = { version = "0.1.1", path = "../tetsy-keccak-hasher" }

[dependencies.tetsy-triehash]
git = "https://github.com/tetcoin/tetsy-common"
rev = "ad4d6c67f5d514df6c890b9174f8f62d8960a8e0"
