[package]
description = "Trait definitions relative the vapory client"
name = "client-traits"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
account-state = { path = "../account-state" }
blockchain = { package = "vapcore-blockchain", path = "../blockchain" }
bytes = { package = "tetsy-bytes", version = "0.1.0" }
call-contract = { version = "0.1.0", package = "vapcore-call-contract", path = "../call-contract" }
common-types = { path = "../types" }
vapcore-db = { path = "../db" }
vapcore-miner = { path = "../../miner" }
vapory-types = "0.8.0"
tetsy-kvdb = "0.3.2"
# tetsy-kvdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
tetsy-registrar = { path = "../../util/tetsy-registrar" }
tetsy-stats = { version = "0.1.0", path = "../../util/stats" }
trace = { path = "../trace" }
tetsy-vm = { version = "0.1.0", path = "../vm" }
