[package]
name = "rlp-compress"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie (Vapory Style)"
license = "GPL-3.0"
documentation = "https://docs.rs/patricia-trie-vapory"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
tetsy-rlp = "0.4.5"
elastic-array = "0.10"
lazy_static = "1.0"
