[package]
description = "Manage validators and sets of validators: creation, calling and validation of contracts, epoch management, proofs and proving"
name = "validator-set"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { path = "../../client-traits" }
common-types = { path = "../../types" }
engine = { path = "../../engine" }
vapabi = "9.0.1"
vapabi-contract = "9.0.0"
vapabi-derive = "9.0.1"
vapory-types = "0.8.0"
vapjson = { path = "../../../json" }
executive-state = { path = "../../executive-state" }
tetsy-keccak-hash = "0.4.0"
tetsy-kvdb = "0.3.2"
# tetsy-kvdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
lazy_static = "1.3.0"
log = "0.4.8"
machine = { path = "../../machine" }
memory-cache = { path = "../../../util/memory-cache" }
tetsy-bytes = "0.1.0"
tetsy-util-mem = "0.3.0"
parking_lot = "0.9"
tetsy-rlp = "0.4.5"
triehash = { package = "triehash-vapory", version = "0.2",  path = "../../../util/triehash-vapory" }
tetsy-unexpected = { path = "../../../util/tetsy-unexpected" }
tetsy-vm = { version = "0.1.0", path = "../../vm" }

[dev-dependencies]
accounts = { package = "vapcore-accounts", path = "../../../accounts" }
call-contract = { package = "vapcore-call-contract", path = "../../call-contract" }
engine = { path = "../../engine", features = ["test-helpers"] }
env_logger = "0.6.2"
vapcore = { path = "../..", features = ["test-helpers"] }
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
tetsy-keccak-hash = "0.4.0"
rustc-hex = "1.0"
spec = { path = "../../spec" }

[features]
test-helpers = []
