[package]
description = "Tetsy Vapory Common Types"
name = "common-types"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
derive_more = "0.15.0"
vapbloom = "0.8.0"
vapcore-io = { path = "../../util/io" }
vapory-types = "0.8.0"
vapjson = { path = "../../json" }
tetsy-keccak-hash = "0.4.0"
tetsy-bytes = "0.1"
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
tetsy-util-mem = "0.3.0"
tetsy-snappy = "0.1"
patricia-trie-vapory = { path = "../../util/patricia-trie-vapory" }
tetsy-rlp = "0.4.5"
tetsy-rlp-derive = { path = "../../util/tetsy-rlp-derive" }
tetsy-unexpected = { path = "../../util/tetsy-unexpected" }
vm = { path = "../vm"}

[dev-dependencies]
rustc-hex = "2.0"

[features]
test-helpers = []
