[package]
description = "Take and restore snapshots of the blockchain and read/write it in chunks from/to disk"
name = "snapshot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[[bench]]
name = "to_fat_rlps"
harness = false

[dependencies]
account-db = { path = "../account-db" }
account-state = { version = "0.1.0", path = "../account-state" }
blockchain = { package = "vapcore-blockchain", path = "../blockchain" }
bloom-journal = { package = "vapcore-bloom-journal", path = "../../util/bloom" }
bytes = { package = "tetsy-bytes", version = "0.1.0" }
client-traits = { path = "../client-traits" }
common-types = { version = "0.1.0", path = "../types" }
crossbeam-utils = "0.6"
engine = { path = "../engine" }
vapcore-db = { version = "0.1.0", path = "../db" }
vapcore-io = { version = "1.12.0", path = "../../util/io" }
vapory-types = "0.8.0"
vaptrie  = { package = "patricia-trie-vapory", path = "../../util/patricia-trie-vapory", version = "0.1.1" }
tetsy-hash-db = "0.15.2"
itertools = "0.5"
journaldb = { path = "../../util/journaldb" }
tetsy-keccak-hash = "0.4.0"
tetsy-keccak-hasher = { path = "../../util/tetsy-keccak-hasher" }
tetsy-kvdb = "0.3.2"
# tetsy-kvdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
log = "0.4.8"
num_cpus = "1.10.1"
rand = "0.7"
rand_xorshift = "0.2"
parking_lot = "0.9"
tetsy-rlp = "0.4.5"
tetsy-rlp-derive = { version = "0.0.1", path = "../../util/tetsy-rlp-derive" }
scopeguard = "1.0.0"
snappy = { package = "tetsy-snappy", version ="0.1.0" }
state-db = { path = "../state-db" }
tetsy-trie-db = "0.19.2"
triehash = { package = "triehash-vapory", version = "0.2",  path = "../../util/triehash-vapory" }

[dev-dependencies]
accounts = { package = "vapcore-accounts", path = "../../accounts" }
criterion = "0.3.0"
engine = { path = "../engine", features = ["test-helpers"] }
env_logger = "0.5"
vapabi = "9.0.1"
vapabi-contract = "9.0.0"
vapabi-derive = "9.0.1"
vapcore = { path = "..", features = ["test-helpers"] }
vapkey = { path = "../../accounts/vapkey" }
tetsy-kvdb-rocksdb = "0.4.3"
# tetsy-kvdb-rocksdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
lazy_static = { version = "1.3" }
spec = { path = "../spec" }
tempdir = "0.3"
tetsy-trie-standardmap = "0.15.2"
# Note[dvdplm]: Ensure the snapshot tests are included in the dependency tree, which in turn means that
# `cargo test --all` runs the tests.
snapshot-tests = { path = "./snapshot-tests" }

[features]
test-helpers = []
