[package]
name = "account-state"
description = "Vapory accounts, keeps track of changes to the code and storage"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"
version = "0.1.0"
edition = "2018"
documentation = "https://docs.rs/account-state"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
common-types = { version = "0.1.0", path = "../types"}
derive_more = "0.15.0"
vapory-types = "0.8.0"
vaptrie = { package = "patricia-trie-vapory", path = "../../util/patricia-trie-vapory", version = "0.1.1" }
trie-vm-factories = { path = "../trie-vm-factories" }
tetsy-hash-db = "0.15.2"
journaldb = { version = "0.2.0", path = "../../util/journaldb" }
tetsy-keccak-hash = "0.4.0"
tetsy-keccak-hasher = { version = "0.1.1", path = "../../util/tetsy-keccak-hasher" }
tetsy-kvdb = "0.3.2"
log = "0.4"
lru-cache = "0.1.2"
tetsy-memory-db = "0.18.1"
tetsy-bytes = "0.1.0"
tetsy-util-mem = "0.3.0"
parking_lot = "0.9"
vapcore-pod = { version = "0.1.0", path = "../pod" }
tetsy-rlp = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
tetsy-trie-db = "0.19.2"

[dev-dependencies]
account-db = { version = "0.1.0", path = "../account-db" }
journaldb = { version = "0.2.0", path = "../../util/journaldb" }
tetsy-bytes = "0.1.0"
rlp-compress = { version = "0.1.0", path = "../../util/rlp-compress" }
