[package]
description = "Engine that seals instantly"
name = "instant-seal"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { version = "0.1.0", path = "../../client-traits" }
common-types = { version = "0.1.0", path = "../../types" }
engine = { version = "0.1.0", path = "../../engine" }
vapjson = { path = "../../../json" }
vapory-types = "0.8.0"
tetsy-keccak-hash = "0.4.0"
mashina = { path = "../../mashina" }
vapcore-trace = { version = "0.1.0", path = "../../trace" }

[dev-dependencies]
vapcore = { path = "../..", features = ["test-helpers"] }
spec = { path = "../../spec" }
tetsy-rlp = "0.4.5"
