[package]
description = "Tetsy Vapory Virtual Machine (VVM) Rust Implementation"
name = "vvm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
bit-set = "0.4"
tetsy-bytes = "0.1"
vapory-types = "0.8.0"
tetsy-util-mem = "0.3.0"
lazy_static = "1.0"
log = "0.4"
vm = { path = "../vm" }
tetsy-keccak-hash = "0.4.0"
parking_lot = "0.9"
memory-cache = { path = "../../util/memory-cache" }

[dev-dependencies]
rustc-hex = "1.0"
criterion = "0.3"
hex-literal = "0.2.0"

[features]
vvm-debug = []
vvm-debug-tests = ["vvm-debug"]

[[bench]]
name = "basic"
harness = false
