[package]
name = "trace"
description = "Transaction tracing"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
vapcore-blockchain = { version = "0.1.0", path = "../blockchain" }
vapcore-db = { version = "0.1.0", path = "../db" }
vapory-types = "0.8.0"
vvm = { version = "0.1.0", path = "../vvm" }
tetsy-kvdb = "0.3.2"
# tetsy-kvdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
log = "0.4"
tetsy-bytes = "0.1.0"
tetsy-util-mem = "0.3.0"
parking_lot = "0.9"
tetsy-rlp = "0.4.5"
tetsy-rlp-derive = { version = "0.0.1", path = "../../util/tetsy-rlp-derive" }
tetsy-vm = { version = "0.1.0", path = "../vm" }

[dev-dependencies]
# Used for test helpers
vapcore = { path = "..", features = ["test-helpers"] }
