[package]
name = "patricia-trie-vapory"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie (Vapory Style)"
license = "GPL-3.0"

[dependencies]
tetsy-trie-db = "0.20.0"
tetsy-keccak-hasher = { version = "0.1.1", path = "../tetsy-keccak-hasher" }
tetsy-hash-db = "0.15.2"
tetsy-rlp = "0.4.5"
tetsy-bytes = "0.1"
vapory-types = "0.8.0"
elastic-array = "0.10"

[dev-dependencies]
tetsy-memory-db = "0.19.0"
tetsy-keccak-hash = "0.4.0"
journaldb = { path = "../journaldb" }
criterion = "0.3"

[[bench]]
name = "rlp_node_codec"
harness = false
