[package]
description = "A vapory engine which does not provide any consensus mechanism and does not seal blocks."
name = "null-engine"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "GPL-3.0"
documentation = "https://docs.rs/null-engine"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
common-types = { version = "0.1.0", path = "../../types" }
block-reward = { version = "0.1.0", path = "../../block-reward" }
enjen = { version = "0.1.0", path = "../../enjen" }
vapjson = { version = "0.1.0", path = "../../../json" }
vapory-types = "0.8.0"
mashina = { version = "0.1.0", path = "../../mashina" }
