[package]
name = "snapshot-tests"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
accounts = { package = "vapcore-accounts", path = "../../../accounts" }
account-db = { path = "../../account-db" }
account-state = { version = "0.1.0", path = "../../account-state" }
blockchain = { package = "vapcore-blockchain", path = "../../blockchain" }
bytes = { package = "tetsy-bytes", version = "0.1.0" }
client-traits = { version = "0.1.0", path = "../../client-traits" }
common-types = { version = "0.1.0", path = "../../types" }
enjen = { version = "0.1.0", path = "../../enjen", features = ["test-helpers"] }
env_logger = "0.5"
vapcore = { path = "../..", features = ["test-helpers"] }
vapcore-db = { version = "0.1.0", path = "../../db" }
vapcore-io = { version = "1.12.0", path = "../../../util/io" }
vapory-types = "0.8.0"
vaptrie  = { package = "patricia-trie-vapory", path = "../../../util/patricia-trie-vapory", version = "0.1.1" }
tetsy-hash-db = "0.15.2"
journaldb = { path = "../../../util/journaldb" }
tetsy-keccak-hash = "0.4.0"
tetsy-keccak-hasher = { version = "0.1.1", path = "../../../util/tetsy-keccak-hasher" }
tetsy-kvdb = "0.3.2"
tetsy-kvdb-rocksdb = "0.4.3"
# tetsy-kvdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
# tetsy-kvdb-rocksdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
log = "0.4.8"
parking_lot = "0.9"
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
rand = "0.7"
rand_xorshift = "0.2"
tetsy-rlp = "0.4.5"
snappy = { package = "tetsy-snappy", version ="0.1.0" }
vapcore-snapshot = { path = "../../snapshot", features = ["test-helpers"] }
spec = { path = "../../spec" }
tempdir = "0.3"
tetsy-trie-db = "0.19.2"
tetsy-trie-standardmap = "0.15.2"
vapabi = "9.0.1"
vapabi-contract = "9.0.0"
vapabi-derive = "9.0.1"
lazy_static = { version = "1.3" }
triehash = { package = "triehash-vapory", version = "0.2",  path = "../../../util/triehash-vapory" }
