[package]
description = "vapory vm builtin"
name = "vapcore-builtin"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
documentation = "https://docs.rs/vapcore-builtin"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
tbn = { version = "0.4.4", default-features = false }
# tbn = { git = "https://github.com/tetcoin/tbn", default-features = false }
byteorder = "1.3.2"
common-types = { version = "0.1.0", path = "../types" }
eip-152 = { version = "0.1.0", path = "../../util/EIP-152" }
vapory-types = "0.8.0"
vapjson = { version = "0.1.0", path = "../../json" }
tetsy-keccak-hash = "0.4.0"
log = "0.4"
num = { version = "0.1", default-features = false, features = ["bigint"] }
tetsy-bytes = "0.1"
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }

[dev-dependencies]
hex-literal = "0.2.1"
tetsy-macros = { version = "0.1.0", path = "../../util/macros" }
