[package]
description = "Vapash PoW blockchain engine"
name = "vapash-engine"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
block-reward = { version = "0.1.0", path = "../../block-reward" }
common-types = { version = "0.1.0", path = "../../types" }
engine = { version = "0.1.0", path = "../../enjen" }
vapash= { path = "../../../vapash" }
vapory-types = "0.8.0"
vapjson = { path = "../../../json" }
tetsy-keccak-hash = "0.4.0"
log = "0.4.8"
mashina = { version = "0.1.0", path = "../../mashina" }
tetsy-macros = { version = "0.1.0", path = "../../../util/macros" }
tetsy-unexpected = { path = "../../../util/tetsy-unexpected" }

[dev-dependencies]
vapcore = { path = "../..", features = ["test-helpers"] }
tetsy-keccak-hash = "0.4.0"
tetsy-rlp = "0.4.5"
spec = { path = "../../spec" }
tempdir = "0.3"
