[package]
name = "tetsy-rlp-derive"
version = "0.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
description = "Testy RLP Derive"
documentation = "https://docs.rs/tetsy-rlp-derive"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[lib]
name = "tetsy_rlp_derive"
proc-macro = true

[dependencies]
syn = "1.0.14"
quote = "1.0.2"
proc-macro2 = "1.0.8"

[dev-dependencies]
tetsy-rlp = "0.4.5"
