[package]
description = "Tetsy Private Transactions"
name = "vapcore-private-tx"
version = "1.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
account-state = { path = "../account-state" }
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
derive_more = "0.14.0"
vapabi = "9.0.1"
vapabi-contract = "9.0.0"
vapabi-derive = "9.0.1"
vapcore = { path = ".." }
vapcore-db = { path = "../db" }
vapcore-call-contract = { path = "../call-contract" }
vapcore-io = { path = "../../util/io" }
vapcore-miner = { path = "../../miner" }
vapory-types = "0.8.0"
vapjson = { path = "../../json" }
tetsy-fetch = { version = "0.1.0", path = "../../util/fetch" }
futures = "0.1"
tetsy-util-mem = "0.3.0"
tetsy-hash-db = "0.15.2"
tetsy-keccak-hash = "0.4.0"
tetsy-keccak-hasher = { path = "../../util/tetsy-keccak-hasher" }
tetsy-kvdb = "0.3.2"
# tetsy-kvdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
log = "0.4"
machine = { path = "../machine" }
journaldb = { path = "../../util/journaldb" }
tetsy-bytes = "0.1"
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
parking_lot = "0.9"
tetsy-trie-db = "0.20.0"
patricia-trie-vapory = { path = "../../util/patricia-trie-vapory" }
tetsy-registrar = { path = "../../util/tetsy-registrar" }
tetsy-rlp = "0.4.5"
tetsy-rlp-derive = { path = "../../util/tetsy-rlp-derive" }
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
spec = { path = "../spec" }
state-db = { path = "../state-db" }
time-utils = { path = "../../util/time-utils" }
tiny-keccak = "1.4"
trace = { path = "../trace" }
transaction-pool = "2.0.1"
url = "2"
vm = { path = "../vm" }

[dev-dependencies]
env_logger = "0.5"
vapcore = { path = "..", features = ["test-helpers"] }
