[package]
description = "Execute transactions producing a receipt and an optional trace."
name = "executive-state"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
documentation = "https://docs.rs/executive-state"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
account-db = { path = "../account-db" }
account-state = { version = "0.1.0", path = "../account-state" }
bytes = { package = "tetsy-bytes", version = "0.1.0" }
common-types = { version = "0.1.0", path = "../types" }
vapory-types = "0.8.0"
tetsy-hash-db = "0.15.2"
tetsy-keccak-hasher = { version = "0.1.1", path = "../../util/tetsy-keccak-hasher" }
tetsy-kvdb = "0.3.2"
# tetsy-kvdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
log = "0.4.8"
machine = { path = "../machine" }
vapcore-trace = { version = "0.1.0", path = "../trace" }
trie-vm-factories = { version = "0.1.0", path = "../trie-vm-factories" }
tetsy-vm = { version = "0.1.0", path = "../vm" }

[dev-dependencies]
env_logger = "0.5"
vapcore = { path = "..", features = ["test-helpers"] }
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
vvm = { version = "0.1.0", path = "../vvm" }
tetsy-keccak-hash = "0.4.0"
vapcore-pod = { version = "0.1.0", path = "../pod" }
rustc-hex = "1.0"
spec = { path = "../spec" }
tetsy-trie-db = "0.19.2"
vaptrie = { package = "patricia-trie-vapory", path = "../../util/patricia-trie-vapory", version = "0.1.1" }
