[package]
description = "Virtual Machines (VM) Support Library"
name = "vm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
tetsy-bytes = "0.1"
vapory-types = "0.8.0"
patricia-trie-vapory = { path = "../../util/patricia-trie-vapory" }
vapjson = { path = "../../json" }
tetsy-rlp = "0.4.5"
tetsy-keccak-hash = "0.4.0"
