[package]
description = "Tetsy Runtime"
homepage = "http://tetcoin.org"
license = "GPL-3.0"
name = "tetsy-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1"
tokio = "0.1.22"
