[package]
name = "vapcore-io"
description = "Vapcore IO library"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
documentation = "https://docs.rs/vapcore-io"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
fnv = "1.0"
mio = { version = "0.6.19", optional = true }
crossbeam-deque = "0.6"
parking_lot = "0.9"
log = "0.4"
slab = "0.4"
num_cpus = "1.8"
timer = "0.2"
time = "0.1"
tokio = "0.1"
futures = "0.1"

