[package]
description = "Vapory state machine"
name = "machine"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[[bench]]
name = "builtin_contract"
harness = false
required-features = ["test-helpers"]

[dependencies]
account-state = { path = "../account-state" }
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
crossbeam-utils = "0.6"
vapabi = "9.0.1"
vapabi-contract = "9.0.0"
vapabi-derive = "9.0.1"
vapcore-builtin = { path = "../builtin" }
vapcore-call-contract = { path = "../call-contract" }
vapcore-io = { path = "../../util/io" }
vapory-types = "0.8.0"
# Used for tests in other crates through the `test-helpers` feature
vapjson = { path = "../../json", optional = true }
vvm = { path = "../vvm" }
tetsy-keccak-hash = "0.4.0"
log = "0.4"
lru-cache = "0.1.2"
tetsy-bytes = "0.1.0"
parking_lot = "0.9"
tetsy-rlp = "0.4.5"
state-db = { path = "../state-db" }
trace = { path = "../trace" }
trie-vm-factories = { path = "../trie-vm-factories" }
vm = { path = "../vm" }

[dev-dependencies]
common-types = { path = "../types", features = ["test-helpers"] }
criterion = "0.3"
vapcore = { path = "../", features = ["test-helpers"] }
vapcore-io = { path = "../../util/io" }
vapjson = { path = "../../json" }
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
tetsy-macros = { version = "0.1.0", path = "../../util/macros" }
rustc-hex = "1.0"
spec = { path = "../spec" }
tempdir = "0.3"
trace = { path = "../trace" }

[features]
test-helpers = ["vapjson"]
