[package]
name = "tetsy-rlp-derive"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[lib]
name = "tetsy_rlp_derive"
proc-macro = true

[dependencies]
syn = "1.0.14"
quote = "1.0.2"
proc-macro2 = "1.0.8"

[dev-dependencies]
tetsy-rlp = "0.4.5"
