[package]
description = "Collection of factories for VM and Tries"
name = "trie-vm-factories"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
tetsy-trie-db = "0.19.2"
vaptrie = { package = "patricia-trie-vapory", path = "../../util/patricia-trie-vapory", version = "0.1.1" }
account-db = { path = "../account-db" }
vvm = { version = "0.1.0", path = "../vvm" }
tetsy-vm = { version = "0.1.0", path = "../vm" }
wasm = { path = "../wasm" }
tetsy-keccak-hasher = { path = "../../util/tetsy-keccak-hasher" }
