[package]
name = "migration-rocksdb"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.4"
tetsy-macros = { path = "../macros" }
tetsy-kvdb = "0.3.2"
tetsy-kvdb-rocksdb = "0.4.3"
# tetsy-kvdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
# tetsy-kvdb-rocksdb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }

[dev-dependencies]
tempdir = "0.3"
