[package]
description = "Tetsy Vapory Keys Generator CLI"
name = "vapkey-cli"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
license = "GPL-3.0"
documentation = "https://docs.rs/vapkey-cli"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
docopt = "1.0"
env_logger = "0.5"
vapkey = { version = "0.4.0", path = "../" }
panic-hook = { version = "0.1.0", path = "../../../util/panic-hook" }
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
tetsy-wordlist="1.3.1"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
threadpool = "1.7"

[[bin]]
name = "vapkey"
path = "src/main.rs"
doc = false
