[package]
description = "Non-instant BFT proof-of-authority blockchain engine"
name = "authority-round"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
block-gas-limit = { path = "../../block-gas-limit" }
block-reward = { path = "../../block-reward" }
client-traits = { path = "../../client-traits" }
common-types = { version = "0.1.0", path = "../../types" }
derive_more = "0.15.0"
vapabi = "9.0.1"
vapabi-contract = "9.0.0"
vapabi-derive = "9.0.1"
vapory-types = "0.8.0"
vapjson = { path = "../../../json" }
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
engine = { path = "../../engine" }
io = { version = "1.12.0", package = "vapcore-io", path = "../../../util/io" }
itertools = "0.5"
tetsy-keccak-hash = "0.4.0"
lazy_static = "1.3.0"
log = "0.4"
lru-cache = "0.1"
machine = { path = "../../machine" }
tetsy-macros = { version = "0.1.0", path = "../../../util/macros" }
tetsy-bytes = "0.1"
parking_lot = "0.9"
rand = "0.7"
tetsy-rlp = "0.4.5"
time-utils = { path = "../../../util/time-utils" }
tetsy-unexpected = { path = "../../../util/tetsy-unexpected" }
validator-set = { path = "../validator-set" }

[dev-dependencies]
accounts = { package = "vapcore-accounts", path = "../../../accounts" }
engine = { path = "../../engine", features = ["test-helpers"] }
env_logger = "0.6.2"
vapcore = { path = "../..", features = ["test-helpers"] }
spec = { path = "../../spec" }
state-db = { path = "../../state-db" }
validator-set = { path = "../validator-set", features = ["test-helpers"] }
serde_json = "1"
