[package]
description = "Virtual Machines (VM) Support Library"
name = "tetsy-vm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
documentation = "https://docs.rs/tetsy-vm"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
tetsy-bytes = "0.1"
vapory-types = "0.8.0"
patricia-trie-vapory = { version = "0.1.1", path = "../../util/patricia-trie-vapory" }
vapjson = { version = "0.1.0", path = "../../json" }
tetsy-rlp = "0.4.5"
tetsy-keccak-hash = "0.4.0"
