[package]
description = "Tetsy Smart Contract based Node Filter, Manage Permissions of Network Connections"
license = "GPL-3.0"
name = "node-filter"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
documentation = "https://docs.rs/node-filter"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
client-traits = { version = "0.1.0", path = "../client-traits" }
common-types = { version = "0.1.0", path = "../types" }
vapcore = { path = ".."}
vapcore-network = { path = "../../util/network" }
vapcore-network-devp2p = { path = "../../util/network-devp2p" }
vapory-types = "0.8.0"
log = "0.4"
parking_lot = "0.9"
vapabi = "9.0.1"
vapabi-derive = "9.0.1"
vapabi-contract = "9.0.0"
lru-cache = "0.1"

[dev-dependencies]
vapcore = { path = "..", features = ["test-helpers"] }
tetsy-kvdb-memorydb = "0.3.2"
# tetsy-kvdb-memorydb = { git = "https://github.com/tetcoin/tetsy-common", rev = "5b2e347" }
vapcore-io = { version = "1.12.0", path = "../../util/io" }
spec = { path = "../spec" }
tempdir = "0.3"
