[package]
description = "Tetsy custom panic hook"
homepage = "http://tetcoin.org"
license = "GPL-3.0"
name = "panic-hook"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
backtrace = "0.3.2"
