[package]
description = "Clique consensus engine"
name = "clique"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { version = "0.1.0", path = "../../client-traits" }
common-types = { version = "0.1.0", path = "../../types" }
vapory-types = "0.8.0"
vapjson = { path = "../../../json" }
tetsy-crypto = { version = "0.4.2", features = ["publickey"] }
engine = { version = "0.1.0", path = "../../enjen" }
tetsy-keccak-hash = "0.4.0"
lazy_static = "1.3.0"
log = "0.4"
lru-cache = "0.1"
mashina = { version = "0.1.0", path = "../../mashina" }
tetsy-macros = { version = "0.1.0", path = "../../../util/macros" }
rand = "0.7"
parking_lot = "0.9"
tetsy-rlp = "0.4.5"
time-utils = { path = "../../../util/time-utils" }
tetsy-unexpected = { path = "../../../util/tetsy-unexpected" }

[dev-dependencies]
vapcore = { path = "../..", features = ["test-helpers"] }
spec = { path = "../../spec" }
state-db = { version = "0.1.0", path = "../../state-db" }
