[package]
name = "tetsy-keccak-hasher"
version = "0.1.1"
edition = "2018"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Tetsy Keccak-256 implementation of the Hasher trait"
license = "GPL-3.0"
documentation = "https://docs.rs/tetsy-keccak-hasher"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
vapory-types = "0.8.0"
tiny-keccak = "1.4.2"
tetsy-hash-db = "0.15.2"
tetsy-plain-hasher = "0.2.1"
