[package]
description = "A crate to interact with the block gas limit contract"
name = "block-gas-limit"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
vapabi = "9.0.1"
vapabi-derive = "9.0.1"
vapabi-contract = "9.0.0"
vapory-types = "0.8.0"
log = "0.4"

[dev-dependencies]
vapcore = { path = "..", features = ["test-helpers"] }
spec = { path = "../spec" }
