[package]
description = "Vapcore WASM Interpreter"
name = "vapcore-wasm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"
edition = "2018"
documentation = "https://docs.rs/vapcore-wasm"
homepage = "https://github.com/openvapory/tetsy-vapory"
repository = "https://github.com/openvapory/tetsy-vapory"

[dependencies]
byteorder = "1.0"
vapory-types = "0.8.0"
log = "0.4"
tetsy-wasm = "0.31.1"
libc = "0.2"
twasm-utils = "0.6.1"
tetsy-vm = { version = "0.1.0", path = "../vm" }
twasmi = "0.3.0"

[dev-dependencies]
env_logger = "0.5"
