[package]
name = "tetsy-keccak-hasher"
version = "0.1.1"
edition = "2018"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Keccak-256 implementation of the Hasher trait"
license = "GPL-3.0"

[dependencies]
vapory-types = "0.8.0"
tiny-keccak = "1.4.2"
tetsy-hash-db = "0.15.2"
tetsy-plain-hasher = "0.2.1"
